sudo: required
services:
  - docker
before_install:
  # openssl serviceaccount.json -d
  # push serviceaccount.json.enc to github and delete original one
  # github asks for user credentials personal access token and correct repository name.
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  # install ruby using docker image
  # the install travis inside container using ruby gem package manager
  # make sure to switch to app folder inside before running above commands
  - gcloud config set project skilful-berm-214822
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo $DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # add docker username and docker password in travisci project settings
  - docker build -t vinaykumar785557/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinaykumar785557/react-test npm test
